# Generated by Django 3.0.2 on 2020-02-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0002_candidatesprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillSetTrainingModules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('courseDuration', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='candidatesprofile',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='joblisting',
            old_name='discription',
            new_name='description',
        ),
    ]
