# Generated by Django 2.2.4 on 2020-02-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0003_auto_20200202_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatesprofile',
            name='jobListing',
            field=models.ForeignKey(null=True, on_delete=None, related_name='job', to='jobs_app.JobListing'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='jobid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
