# Generated by Django 2.2.4 on 2020-02-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0004_auto_20200218_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatesprofile',
            name='skillSetTrainingModules',
            field=models.ForeignKey(null=True, on_delete=None, related_name='skillset', to='jobs_app.SkillSetTrainingModules'),
        ),
        migrations.AddField(
            model_name='skillsettrainingmodules',
            name='skillid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
