# Generated by Django 2.2.4 on 2020-02-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0007_auto_20200219_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatesprofile',
            name='cover',
        ),
        migrations.AddField(
            model_name='candidatesprofile',
            name='resume',
            field=models.FileField(default='0', upload_to='resume'),
        ),
    ]
