# Generated by Django 2.2.4 on 2020-02-19 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0008_auto_20200219_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatesprofile',
            old_name='skillSetTrainingModules',
            new_name='technology',
        ),
        migrations.RenameField(
            model_name='candidatesprofile',
            old_name='jobListing',
            new_name='title',
        ),
    ]
