# Generated by Django 2.2.4 on 2020-02-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0009_auto_20200219_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='id',
        ),
        migrations.RemoveField(
            model_name='skillsettrainingmodules',
            name='id',
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='jobid',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skillsettrainingmodules',
            name='skillid',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
